name: Publish to GitHub Pages

on:
  schedule:
    - cron:  '0 0 * * *'

  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: fabacab/jekyll-builder-for-github-pages-action@master
        with:
          secret_gh_pages_api_token: ${{ secrets.GH_PAGES_TOKEN }}
